name: Convert images to WebP and AVIF

on:
  push:
    branches:
      - "*"

jobs:
  convert_images_to_webp_and_avif:
    runs-on: ubuntu-latest
    steps:
      - name: Check if commit is from bot
        id: is_bot_commit
        run: echo "is_bot_commit=$(git log --pretty=%s -1 | grep 'Convert images to WebP and AVIF')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          lfs: true

      - name: Install cwebp and cavif
        run: |
          sudo apt-get update -y
          sudo apt-get install -y webp
          curl -sSL https://github.com/kornelski/cavif-rs/releases/latest/download/cavif_1.5.1_amd64.deb -o cavif.deb
          sudo dpkg -i cavif.deb

      - name: Check if images have changed
        id: images_changed
        if: ${{ env.is_bot_commit }} != 'is_bot_commit=Convert images to WebP and AVIF'
        run: |
          cd umh.docs.umh.app/static/images
          git diff --quiet HEAD~1 || echo "images_changed=true" >> $GITHUB_ENV

      - name: Convert images to WebP and AVIF
        if: ${{ env.images_changed }} == 'images_changed=true' && ${{ env.is_bot_commit }} != 'is_bot_commit=Convert images to WebP and AVIF'
        run: |
          cd umh.docs.umh.app/static/images
          find . -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png \) \
          | xargs -P 4 -I {} sh -c '
              file="$1"
              new_file=$(echo $file | sed "s/\.[^.]*$/.webp/")
              cwebp -quiet -q 80 "$file" -o "$new_file"
              cavif --overwrite "$file"
            ' _ {}  

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ env.images_changed }} == 'images_changed=true' && ${{ env.is_bot_commit }} != 'is_bot_commit=Convert images to WebP and AVIF'
        with:
          commit_message: "Convert images to WebP and AVIF"
          commit_options: "--no-verify"
          branch: ${{ github.head_ref }}
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com