name: Update search

on:
  push:
    branches:
      - main
      - fix/xxx/search
  # Run every night at 3:00 AM
  schedule:
    - cron: "0 3 * * *"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Docker command
        env:
          TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
          TYPESENSE_HOST: docsearch.umh.app
          TYPESENSE_PORT: 443
          TYPESENSE_PROTOCOL: https
        run: |
          COLLECTION=$(cat config-umh.docs.json | jq -r '.index_name')
          curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
          -X DELETE \
          "${TYPESENSE_PROTOCOL}://${TYPESENSE_HOST}/collections/${COLLECTION}"
          CONFIG=$(cat config-umh.docs.json | jq -r tostring)
          docker run -it -e "CONFIG=$CONFIG" --network host typesense/docsearch-scraper
